version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk:alpine
    working_directory: ~/gradleupdate
    steps:
      - run:
          name: Install
          command: |
            apk --update add openjdk8
            gcloud components install app-engine-java

      - checkout

      - run:
          name: Build
          command: |
            ./gradlew build

      - deploy:
          name: Deploy
          command: |
            gcloud config set project "$GCP_PROJECT_ID"
            echo "$GCP_SERVICE_ACCOUNT_KEY" | base64 -d > "$HOME/gcp-service-account-key.json"
            gcloud auth activate-service-account --key-file "$HOME/gcp-service-account-key.json"
            echo "gradleupdate.github.accessToken=$SYSTEM_GITHUB_ACCESS_TOKEN" >> .properties
            ./gradlew appengineDeploy
